image: mcr.microsoft.com/playwright/java:v1.50.0

stages:
  - test

variables:
  MAVEN_CLI_OPTS: "-B -V"
  HEADLESS: "true"

# Job to run TAS
run_tas:
  stage: test
  script:
    - mvn test -Dtest=GamesTest
